
package com.oracle.xmlns.carrierbilling.bpel_gestioncobroconfirmacion;

import javax.xml.ws.WebFault;

import pe.com.entel.soa.data.generico.entelfault.v1.EntelFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebFault(name = "entelFault", targetNamespace = "http://entel.com.pe/soa/data/generico/entelFault/v1/")
public class EntelFaultMessage extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private EntelFault faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public EntelFaultMessage(String message, EntelFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EntelFaultMessage(String message, EntelFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: pe.com.entel.soa.data.generico.entelfault.v1.EntelFault
     */
    public EntelFault getFaultInfo() {
        return faultInfo;
    }

}
